language: node_js
node_js: 'stable'
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli@1
- gulp lint-eslint
script:
- node ./node_modules/.bin/polymer test --npm --module-resolution=node -l chrome